# Generated by Django 3.2.7 on 2022-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
