# Generated by Django 4.0.1 on 2022-01-10 06:33

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_user_checked_by_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.jpeg', null=True, upload_to=poll.models.user_directory_path),
        ),
    ]
